#pragma once

#include "main.h"

#define DEFLATE_MIN_COMPARE 1
#define DEFLATE_MAX_COMPARE 1500

#define DEFLATE_GREEDY_COMPARE_THRESHOLD 4

#define DEFLATE_SIG_INIT 0x12345678
#define DEFLATE_SIG_DONE 0xABCD1234
